### ISSUE TITLE
Foto (exibição específica)

### ISSUE THREAD

**Issue by meuzent** [felipemrvieira/governo-de-alagoas-cliente#42]
**- Legenda para foto (opção não obrigatória para o gestor de conteúdo)**
  - Caso ele escolha **não colocar legenda**, O título da galeria deve ser atribuído como legenda
  - Ver a possibilidade de inserir uma legenda para todas as fotos e/ou para fotos específicas.

- Credito da foto abaixo do titulo da galeria (fotos: fulano)

- Galeria destaque na home (definir isso na publicação da galeria)

**Comment by rubemfsv** [comment]
Issue duplicada.
https://github.com/felipemrvieira/governo-de-alagoas-cliente/issues/57
